#
# CMS Pages
#
cms_pages:
  lock_attributes: true

  attributes:
    - name: name
      type: string
    - name: slug
      type: string
    - name: layout
      type: string
    - name: version
      type: integer
    - name: published
      type: boolean
      default: true

    # SEO
    - name: keywords
      type: string
    - name: description
      type: string

  relationships:
    has_many: cms_page_widgets

#
# CMS Page Widgets
#
cms_page_widgets:
  attributes:
    - name: klass
      type: string
    - name: published
      type: boolean
      default: true

  relationships:
    belongs_to: cms_pages
